---
- name: Set up macOS
  hosts: all
  become: yes
  tasks:
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install Homebrew packages
      homebrew:
        name:
          - nvm
          - git
          - wget
          - ack
        state: present

    - name: Install Homebrew Cask packages
      homebrew_cask:
        name:
          - visual-studio-code
          - google-chrome
          - brave-browser
          - hyper
          - anaconda
          - postman
          - raycast
        state: present
